development:
  title: "Hunter just rocks"
  twitter_consumer_key: "JdHWtXdiKX8quvB7A9JJzw"
  twitter_consumer_secret: "tvF30OMIF9X0Bo0e9PqexHeOrKiNi7CA3BoT3cDw8"
  twitter_access_token: "146314256-eGlqcd42AfgXQVN9f6tmrsY1AfnfDOtB0IYCkGKN"
  twitter_access_secret: "h5AIbwI5YVhb39F8AjgKl27REBmfn4bWOrsqyaTu3qUnj"